users:
  - name: vhive
    groups: [sudo]
    shell: /bin/bash
    lock_passwd: false
    ssh_pwauth: True
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: "$6$IAZRmy6FncdFuSZr$5uyvklVZY3v1aiQ3IQQ1WiMxD8Kiic28PAy/ODG/tsYrAd2t/Scr/RZspv2JlsKVeX1oEiCiGWaTfz7KKbT9T1"
ssh_pwauth: True
runcmd:
  - sudo apt install -y pip tmux
  - sudo -u invitro bash -c 'cd ~ && tmux new-session -d -s invitro && tmux send-keys -t invitro "curl -O -L https://raw.githubusercontent.com/vhive-serverless/sosp-tutorial-infra-setup/main/install_vhive_invitro.sh && chmod +x install_vhive_invitro.sh && ./install_vhive_invitro.sh" C-m'