users:
  - name: invitro
    groups: [sudo]
    shell: /bin/bash
    lock_passwd: false
    ssh_pwauth: True
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: "$6$k4YGz1JJ2q6Y5hKy$pAwAJdkZIVJkHHv6NoWA2w93paZ8FRk2T1NwBjqaa1fNhi/IJGLQ9RbspbAk1en67MSysoh/uMAV2vQiOj1EW/"
ssh_pwauth: True
runcmd:
  - sudo apt install -y pip tmux
  - sudo -u invitro bash -c 'cd ~ && tmux new-session -d -s invitro && tmux send-keys -t invitro "curl -O -L https://raw.githubusercontent.com/vhive-serverless/sosp-tutorial-infra-setup/main/install_vhive_invitro.sh && chmod +x install_vhive_invitro.sh && ./install_vhive_invitro.sh" C-m'