users:
  - name: vhive
    groups: [sudo]
    shell: /bin/bash
    lock_passwd: false
    ssh_pwauth: True
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: "$6$rounds=4096$5i6ttPGXEVgl3oab$UxN37RWJVtKNII.93HR2YJkt/qbE7EFjMS.AIl1Xvlx4GzRO3LzJIvyYVCBNhuaj3E8fu6T9d4B53DX1TY1rv."
ssh_pwauth: True
runcmd:
  - sudo apt install -y tmux
  - sudo -u vhive bash -c 'cd ~ && tmux new-session -d -s vhive && tmux send-keys -t vhive "git clone --depth=1 https://github.com/vhive-serverless/sosp-tutorial-infra-setup ~/sosp-tutorial-infra-setup && chmod +x ~/sosp-tutorial-infra-setup/vHive_hands_on/setup_vhive_vm.sh && ~/sosp-tutorial-infra-setup/vHive_hands_on/setup_vhive_vm.sh && export PATH=$HOME/.istioctl/bin:$PATH" C-m'
