users:
  - name: invitro
    groups: [sudo]
    shell: /bin/bash
    lock_passwd: false
    ssh_pwauth: True
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: "$6$k4YGz1JJ2q6Y5hKy$pAwAJdkZIVJkHHv6NoWA2w93paZ8FRk2T1NwBjqaa1fNhi/IJGLQ9RbspbAk1en67MSysoh/uMAV2vQiOj1EW/"
ssh_pwauth: True
runcmd:
  - sudo apt install -y pip tmux
  - sudo -u invitro bash -c 'cd ~ && tmux new-session -d -s invitro && tmux send-keys -t invitro "mkdir -p vhive && git clone https://github.com/dilinade/vhive_tutorial vhive/ && cd vhive/ && chmod +x setup_vhive.sh && ./setup_vhive.sh" C-m'