users:
  - name: vhive
    groups: [sudo]
    shell: /bin/bash
    lock_passwd: false
    ssh_pwauth: True
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: "$6$rounds=4096$5i6ttPGXEVgl3oab$UxN37RWJVtKNII.93HR2YJkt/qbE7EFjMS.AIl1Xvlx4GzRO3LzJIvyYVCBNhuaj3E8fu6T9d4B53DX1TY1rv."
ssh_pwauth: True
runcmd:
  - sudo apt install -y pip tmux
  - sudo -u vhive bash -c 'cd ~ && tmux new-session -d -s invitro && tmux send-keys -t invitro "curl -O -L https://raw.githubusercontent.com/vhive-serverless/invitro/refs/heads/sesame25-tutorial/install_vhive_invitro.sh && chmod +x install_vhive_invitro.sh && ./install_vhive_invitro.sh" C-m'